export default {
  // News Sources
  GET_SOURCES_INIT: 'GET_SOURCES_INIT',
  GET_SOURCES_SUCCESSFUL: 'GET_SOURCES_SUCCESSFUL',
  GET_SOURCES_FAILED: 'GET_SOURCES_FAILED',

  // News List
  GET_NEWS: 'GET_NEWS',
  GET_NEWS_SUCCESSFUL: 'GET_NEWS_SUCCESSFUL',
  GET_NEWS_FAILED: 'GET_NEWS_FAILED'
}
